### ISSUE TITLE
support for bootstrapping service with a load balancer

### ISSUE THREAD

**Issue by matl33t** [lumoslabs/broadside#37]
Currently bootstrap only works with services that do not need a load balancer. Because ECS does not allow modification of a service at a later point to attach to a load balancer, this needs to be done at creation.

**Comment by apurvis** [comment]
probably the easiest thing to do would be to add a `load_balancer_config:` key to `Target`... then when you go to deploy broadside can check if the configured ELB is actually set up on the targeted service and fail if not.

if bootstrapping the service, you can use the [AWS ELBv2 API](http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html) to set up the load balancer prior to the service setup, then use the configured ELB in the service bootstrap.  

doesn't sound _that_ hard but probably most of a day's work so it really depends on how much time you're wasting setting up ELBs right now.

**Comment by slpsys** [comment]
oh, damn. i just ran into this now.

**Comment by slpsys** [comment]
Ok, with proper instructions/documentation, this is possible just with the changes in #83. Your config needs to be correct, and you need that extra code to strip off the service definition attributes that ECS doesn't allow for update (ELB, IAM). That PR isn't _done_, but it works. 

I have my example service config (almost exactly real, minus image location and ECS cluster name) [here](https://gist.github.com/slpsys/198704b444fce38cff88dea6b9f0dbc7) for posterity/public view. We're just running [this Redshift maintenance app](https://github.com/everythingme/redshift_console) in our cluster. It's pretty well annotated, but I can add more information, if necessary. This probably *should* go in the docs somewhere, after #83 is spec'd out and merged, because it took ~2h of reading docs and experimenting for me.

**Comment by apurvis** [comment]
should we resolve this?
