### ISSUE TITLE
container_definitions should allow `name` overrides

### ISSUE THREAD

**Issue by slpsys** [lumoslabs/broadside#81]
In `configured_container_definition`, the name is [always set to the family](https://github.com/lumoslabs/broadside/blob/2ff75e1/lib/broadside/ecs/ecs_deploy.rb#L201).

I was poking around in #37 earlier this morning--and I think this is actually already possible if you've already got an ELB set up--BUT the biggest issue is that you need the container name inside your task definition and the `container_name` inside the `load_balancers` portion of the service definition to match . This is *knowable*, currently, because the `container_name` is derived, and is just `"#{application}_#{target}"`, but this is both subject to potential change and also, frankly, annoying. I'd rather be able to override it like:

```
web: {
      service_config: {
        role: 'ecsServiceRole',
        load_balancers: [
          {
            container_name: 'my-app',
            container_port: 5000,
            ...
          }
        ]
      },
      task_definition_config: {
        container_definitions: [
          {
            name: 'my-app',
```

Right now, i'd have to set the `web.service_config.load_balancers.container_name` to be `my-app_web`. 

Opening as an issue because this is up for debate; not hard to do (`merge` then `reverse_merge`?), but it's policy, not code.

**Comment by apurvis** [comment]
given that https://github.com/lumoslabs/broadside/pull/83 (about adding ELBs to broadside) is really just speculative, it would probably be good to think about generally how ELBs could and should be set up.

Very worth mentioning is that right now [broadside will barf if your `task_definition_config` has more than 1 container in it](https://github.com/lumoslabs/broadside/blob/master/lib/broadside/target.rb#L35-L37).  that was the easy way out of what is an otherwise complicated situation that hasn't come up yet, but if that assumption needed to be changed (and > 1 container could exist) this issue would probably be super relevant and maybe the solution in https://github.com/lumoslabs/broadside/pull/83 would be unacceptable.

cc @matl33t

**Comment by slpsys** [comment]
> given that #83 (about adding ELBs to broadside) is really just speculative, it would probably be good to think about generally how ELBs could and should be set up.

i think this comment was before our [very long] conversation in Slack, which clarifies what #83 does, I believe?

**Comment by slpsys** [comment]
Actually, I don't think that comment addresses what this issue was about, at all? This is just about allowing you to override the Task Definition container name, when you specify it.

**Comment by matl33t** [comment]
It's a hard requirement that the load balancer container name maps to the configured container name. In broadside's case we use the `family` (https://github.com/lumoslabs/broadside/wiki/AWS%20Setup#terminology). This same name is also used for the service name and task definition name. I think the right course of action will just be to emphasize this requirement in the docs.

**Comment by slpsys** [comment]
👍
